### ISSUE TITLE
[MC 1.11.2] PurpleIRC causing other mods to crash

### ISSUE THREAD

**Issue by sandalle** [cnaude/PurpleIRC-forge#11]
When I add PurpleIRC 1.11.2-1.0-SNAPSHOT to my client, it causes other mods (e.g. PlusTiC and Recurrent Complex) to crash on load. My server loads fine.

PlusTiC: [crash-2017-06-23_18.09.55-client.txt](https://github.com/cnaude/PurpleIRC-forge/files/1099338/crash-2017-06-23_18.09.55-client.txt) (mis-reported to https://github.com/Landmaster/PlusTiC/issues/54 )
Recurrent Complex (after disabling PlusTiC, thinking that was the issue): 
[crash-2017-06-23_18.16.39-client.txt](https://github.com/cnaude/PurpleIRC-forge/files/1099339/crash-2017-06-23_18.16.39-client.txt)

Disabling PurpleIRC in my client allows my client to load without issue.

**Comment by cnaude** [comment]
I have some ideas about this. I will let you know when there is a new version to test.

**Comment by sandalle** [comment]
Still crashes with purpleirc-1.11.2-1.0-4.jar: [crash-2017-06-23_19.40.41-client.txt](https://github.com/cnaude/PurpleIRC-forge/files/1099380/crash-2017-06-23_19.40.41-client.txt)

Here are the ZIPped mods (still testing for my next release of https://minecraft.curseforge.com/projects/nst-unofficial-exploration , I haven't tested with those older versions to see if I get the same crash): https://www.dropbox.com/s/hx38oidg265eu56/mods.zip?dl=0

And the ZIPped configs: https://www.dropbox.com/s/t3ssvbpa6urvuln/config.zip?dl=0

**Comment by cnaude** [comment]
I figured out exactly where the problem is. This mod was never originally intended for client side use. The reason it crashes is because it's trying to access server classes that don't exist in client mode. I'm working on adding the client side checks.

**Comment by sandalle** [comment]
I believe https://github.com/cnaude/PurpleIRC-forge/issues/5 has information and a request to make this a server-side only mod, even if a client tries to load it. 😉 Thank you for taking a look!

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/PurpleIRC-forge-1.11.2/5/

**Comment by sandalle** [comment]
PurpleIRC 1.11.2-1.0-5 works on both server and client (client loads without crashing), thanks!
