### ISSUE TITLE
Request update

### ISSUE THREAD

**Issue by Elvi81** [cnaude/PurpleIRC-forge#13]
This is not an issue per say but could you update purpleirc for forge 1.12.2?
Just in case you didn't know, the 1.11.2 version does not work at all with 1.12.2, instant crash on modpack server.

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/PurpleIRC-forge-1.12.2/

**Comment by Elvi81** [comment]
Does this on every command, can't even connect.
https://pastebin.com/SCMYrYVP

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/PurpleIRC-forge-1.12.2/3/artifact/build/libs/purpleirc-1.12.2-1.0-3.jar

**Comment by Elvi81** [comment]
https://pastebin.com/mCufZ9Q3

Same deal, errors when using the commands from client but works in console, does connect but does not join the channel on startup, mod pack is modern skyblock 3, a huge pack, takes some time to load.

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/PurpleIRC-forge-1.12.2/4/artifact/build/libs/purpleirc-1.12.2-1.0-4.jar

**Comment by Elvi81** [comment]
Client side commands work now, don't know why it refuses to connect fully on startup though, have to manualy reconnect to make it work.

**Comment by cnaude** [comment]
What is the exact version of Forge you are running?

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/PurpleIRC-forge-1.12.2/5/artifact/build/libs/purpleirc-1.12.2-1.0-5.jar

Latest version uses newer IRC libs.

**Comment by Elvi81** [comment]
Same, does auto connect to irc server but does not join channel, reloadbot needed.
Maybe a delay is needed to have the server fully load first, takes a few minutes.

Forge 14.23.2.2635

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/PurpleIRC-forge-1.12.2/7/artifact/build/libs/purpleirc-1.12.2-1.0-7.jar
This should auto join the channel correctly.
