### ISSUE TITLE
[MC 1.12.2] PurpleIRC 1.12.2-1.0-6 doesn't autojoin channel

### ISSUE THREAD

**Issue by CraigorNZ** [cnaude/PurpleIRC-forge#16]
Hi,

I seem to be having the same issue as #12 with the 1.12.2 version

It won't autojoin, but does if I manually run _irc reloadbots_

**Comment by cnaude** [comment]
HI, what mod pack are you running this under? I've been unable to reproduce this issue on a vanilla forge-1.12.2 server.

**Comment by CraigorNZ** [comment]
Two different Feed The Beast Modpacks, FTB Revelation and FTB Pyramid Reborn

They both behave the same way, I can see on the IRC server that they are connecting to it, but they just don't autojoin the channel

**Comment by cnaude** [comment]
That helps a lot. I'm able to replicate the problem with FTB Pyramid. Now I just need to figure out why it's acting so strange.

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/PurpleIRC-forge-1.12.2/7/artifact/build/libs/purpleirc-1.12.2-1.0-7.jar

**Comment by CraigorNZ** [comment]
That has fixed it for both modpacks

Awesome, thanks!
