### ISSUE TITLE
Crash on first launch 

### ISSUE THREAD

**Issue by cauliflower69** [cnaude/PurpleIRC-forge#7]
http://pastebin.com/AkPWV3TM

**Comment by cnaude** [comment]
What version of forge is this occurring on?

**Comment by cauliflower69** [comment]
1.9 - 12.16.1.1907

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/PurpleIRC-forge-1.9/9/

**Comment by cauliflower69** [comment]
Will do, thanks

**Comment by cauliflower69** [comment]
Launched fine now, thanks
